### ISSUE TITLE
Création d'une commande impossible sur Jeedom bêta 2.0

### ISSUE THREAD

**Issue by dough29** [jeedom/plugin-geoloc#2]
Bonjour,

je suis actuellement en train de tester un peu Jeedom 2.0 (qui semble pointer le bout de son nez les prochains jours !). Par curiosité je me suis monté un Jeedom 2.0 sur mon NAS Synology (via Docker et le paquet suivant : https://hub.docker.com/r/jeedom/jeedom/

L'installation s'est bien déroulée, j'ai ajouté le plugin Geoloc et je constate qu'il est impossible d'ajouter une commande : le formulaire apparaît bien, je saisis un nom - fixe - les coordonnées et clique sur "Sauvegarder" -> l'écran s'actualise mais au lien de conserver ma nouvelle commande elle disparaît.

Il n'y a aucun message d'erreur, je peux fouiller dans les logs si besoin.

**Comment by zoic21** [comment]
Bonjour,
Si tu n'es pas betatesteur tu n'as pas accès aux au plugins en beta (a moins de prendre la version du git) donc il est possible que ca ne marche pas bien avec jeedom 2.0

**Comment by dough29** [comment]
D'accord de comprends mieux.

Il y a un GIT dédié ? Car le plugin n'a pas de branche beta ici.

Si vous avez des besoins pour tester je suis partant.

**Comment by zoic21** [comment]
Non c'est ce git la, le git est toujours en beta

**Comment by dough29** [comment]
Bonjour,
j'ai profité de la sortie de la version 2.0 pour me faire une installation toute fraîche de Jeedom et je constate que j'ai toujours le même problème qu'évoqué  dans le 1er message.
Je suis bien en version stable.
Cordialement.

**Comment by zoic21** [comment]
Je viens de tester et je n'arrive pas a reproduire.
